import "../styles/main.css";
import HeaderWithShoppingCartProvider from "@/ui/header/HeaderWithProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeaderWithShoppingCartProvider />
        <main>{children}</main>
      </body>
    </html>
  );
}
